name: Deploy to Minikube using GitHUB Actions - KMI

on:
  push:
     branches: [ "master" ]
  workflow_dispatch:

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
      - name: Start minikube
        uses: medyagh/setup-minikube@master
        with:
           driver: docker

      - name: Try the cluster 
        run: kubectl get nodes

      - name: Build image
        run: |
          export SHELL=/bin/bash
          eval $(minikube -p minikube docker-env)
          docker build -f ./Dockerfile -t devopshint/node-app:latest .
          echo  "verifying images:"
          docker images 

      - name: Deploy to minikube
        run: |
          kubectl apply -f k8s-node-app.yaml
          kubectl get pods -A

      - name: Test service URLs
        run: |
          minikube service list
          minikube service nodejs-app --url
  
